version: "3.7"
services:
  postgres-db:
    image: postgres:15.3-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=backend
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
  
  spring-app:
    #image: backend-prod:latest
    image: alextozetti/backend-prod:latest
    ports: 
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/backend
    depends_on:
      - postgres-db
  
  spa-app:
    image: alextozetti/frontend-prod:latest
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - spring-app
